[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  REACT_APP_SUPABASE_URL = ""
  REACT_APP_SUPABASE_ANON_KEY = ""
  REACT_APP_ENV = "production"

# Configurações para SPA React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuração para APIs Python
[[redirects]]
  from = "/api/pdf/*"
  to = "/.netlify/functions/pdf-processor/:splat"
  status = 200

[[redirects]]
  from = "/api/automation/*"
  to = "/.netlify/functions/automation/:splat"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"

# Headers para arquivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para PDFs
[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=86400"

# Configurações de build context
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Configurações de formulários Netlify
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Configurações para uploads de PDF
[[edge_functions]]
  function = "pdf-upload"
  path = "/api/upload/*"
