# netlify.toml - Configuração de Deploy do Sistema EBD
[build]
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

# Variáveis de ambiente (configure no painel do Netlify)
# REACT_APP_SUPABASE_URL
# REACT_APP_SUPABASE_ANON_KEY

# Redirecionamentos para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache para arquivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://sifneeexxbqgscqinbwm.supabase.co;"

# Cache para PDFs
[[headers]]
  for = "*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/pdf"
